openapi: 3.0.3

info:
  version: '1.0.0'
  title: Nowqtt Bridge
  description: Get Nowqtt log data

servers:
  - url: '/{basePath}'
    description: API server
    variables:
        basePath:
          default: v1

tags:
  - name: Traces
  - name: Devices
  - name: DevicesNames
  - name: Activity

paths:
  /traces:
    get:
      summary: Get a list of traces
      description: Retu   rns a list of traces
      tags:
        - Traces
      parameters:
        - name: device_mac_address
          in: query
          required: false
          schema:
            type: string
            minLength: 12
            maxLength: 12
        - name: last
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
      responses:
        200:
          description: A list of traces
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Traces'
        500:
          description: Internal server error

  /devices:
    get:
      summary: Get a list of devices
      description: Returns a list of devices
      tags:
        - Devices
      responses:
        200:
          description: A list of devices
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        mac_address:
                          type: string
                        name:
                          type: string
        500:
          description: Internal server error

  /devices/{device_mac_address}/names:
    parameters:
      - name: device_mac_address
        in: path
        schema:
          type: string
        required: true
        description: Mac_address for the name
    get:
      summary: Get a list of devices names
      description: Returns a list of devices names
      tags:
        - DevicesNames
      responses:
        200:
          description: A list of devices names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Devices_Names'

    patch:
      summary: Add a device name
      description: Add a device name
      tags:
        - DevicesNames
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        201:
          description: Add a device name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Devices_Names'

    delete:
      summary: Delete a device name
      description: Delete a device name
      tags:
        - DevicesNames
      responses:
        204:
          description: Add a device name

  /devices/names:
    get:
      summary: Get a list of devices names
      description: Returns a list of devices names
      tags:
        - DevicesNames
      responses:
        200:
          description: A list of devices names
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Devices_Names'

  /devices/activity:
    get:
      summary: Get the activity log of devices
      description: Returns the activity log of devices
      tags:
        - Activity
      parameters:
        - name: device_mac_address
          in: query
          required: false
          schema:
            type: string
            minLength: 12
            maxLength: 12
        - name: last
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
      responses:
        200:
          description: A list of activities
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Devices_Activity'

  /ota/update/{device_mac_address}:
    parameters:
     - name: device_mac_address
       in: path
       schema:
         type: string
       required: true
       description: Mac_address of the device that should be updated
    post:
     summary: OTA update a device
     description: Start a OTA update for a device with a given MAC address and binary
     requestBody:
       content:
         multipart/form-data:
           schema:
             type: object
             properties:
               file:
                 type: string
                 format: binary
                 description: Binary file for OTA
           encoding:
             file:
               contentType: application/octet-stream
       required: true
     responses:
       '200':
         description: File for OTA update received

components:
  schemas:

    Traces:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        dest_mac_address:
          type: string
        name:
          type: string
        timestamp:
          type: string
        hops:
          $ref: '#/components/schemas/Hops'

    Hops:
      type: array
      items:
        type: object
        properties:
          hop_counter:
            type: integer
          hop_mac_address:
            type: string
          name:
            type: string
          hop_rssi:
            type: integer
          hop_dest_seq:
            type: integer
          route_age:
            type: integer
          hop_count:
            type: integer

    Devices_Names:
      type: object
      properties:
        name:
          type: string
        mac_address:
          type: string

    Devices_Activity:
      type: object
      properties:
        name:
          type: string
        mac_address:
          type: string
        timestamp:
          type: string
        activity:
          type: integer
